const ourLeaders = [
  {
    image: 'AliaksandrArashkevich',
    name: 'Alex Oreshkevich',
    position: 'CEO in Administration',
    department: 'Administration',
    linkedIn: '',
    post: '',
    alt: 'Alex Oreshkevich CEO and Founder at REDNAVIS company'
  },
  {
    image: 'DariaKrivetskaya',
    name: 'Daria Krivetskaya',
    position: 'HR manager',
    department: 'HR Department',
    linkedIn: 'https://www.linkedin.com/in/dasha-krivetskaya-428920155/',
    post: 'dasha.krivetskaya@rednavis.com',
    alt: 'Daria Krivetskaya HR manager at REDNAVIS company'
  },
  {
    image: 'KonstantinKotov',
    name: 'Konstantin Kotov',
    position: 'Software engineer',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
    alt: 'Konstantin Kotov Software engineer at REDNAVIS company'
  },
  {
    image: 'AleksanderSavkov',
    name: 'Aleksander Savkov',
    position: 'Software engineer',
    department: 'Front End Department',
    linkedIn: '',
    post: '',
    alt: 'Alexandr Saukou Software engineer at REDNAVIS company'
  },
  {
    image: 'DzmitryTsydzik',
    name: 'Dzmitry Tsydzik',
    position: 'Lead software engineer',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
    alt: 'Dmitry Tsydzik Lead Software engineer at REDNAVIS company'
  },
  {
    image: 'AlexeyLabotski',
    name: 'Alexey Labotski',
    position: 'Software engineer',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
    alt: 'Aliaksei Labotski Software engineer at REDNAVIS company'
  },
  {
    image: 'SiarheiPetrashka',
    name: 'Siarhei Petrashka',
    position: 'Software engineer',
    department: 'Front End Department',
    linkedIn: '',
    post: '',
    alt: 'Sergey Petrashko Software engineer at REDNAVIS company'
  },
  {
    image: 'AlexeyShalak',
    name: 'Alexey Shalak',
    position: 'Software engineer',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
    alt: 'Aliaksei Shalak Software engineer at REDNAVIS company'
  },
  {
    image: 'AleksandrSmirnov',
    name: 'Aleksandr Smirnov',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'DmitryOreshkevich',
    name: 'Dmitry Oreshkevich',
    position: 'Deputy director in Administration',
    department: 'Administration',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AnnaKorzhenevskaya',
    name: 'Anna Korzhenevskaya',
    position: 'Business development manager in Administration',
    department: 'Sales Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'YuryGrishechkin',
    name: 'Yury Grishechkin',
    position: 'Sales manager in Administration',
    department: 'Sales Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'VladimirBondarchik',
    name: 'Vladimir Bondarchik',
    position: 'Business Analysit in BA department',
    department: 'Business Analysit Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'ElizavetaCherneta',
    name: 'Elizaveta Cherneta',
    position: 'Business Analysit in BA department',
    department: 'Business Analysit Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'DmitryUngur',
    name: 'Dmitry Ungur',
    position: 'Business Analysit in BA department',
    department: 'Business Analysit Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AndreyLysyuk',
    name: 'Andrey Lysyuk',
    position: 'Software engineer in Software development Department',
    department: 'Front End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AntonKishkurno',
    name: 'Anton Kishkurno',
    position: 'Software development Department',
    department: 'Front End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'VladaBratova',
    name: 'Vlada Bratova',
    position: 'Recruiter in HR department',
    department: 'HR Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'ValeriaGorban',
    name: 'Valeria Gorban',
    position: 'Recruiter in HR department',
    department: 'HR Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'IrinaMalesha',
    name: 'Irina Malesha',
    position: 'Recruiter in HR department',
    department: 'HR Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'YevgeniyaSolovyova',
    name: 'Yevgeniya Solovyova',
    position: 'QA engineer in Software development Department',
    department: 'QA Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'EvgeniyaDudarevich',
    name: 'Evgeniya Dudarevich',
    position: 'Accountant in Administration',
    department: 'Accountant Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AlexeyBelikov',
    name: 'Alexey Belikov',
    position: 'Lead software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'NikitaHerasiutsin',
    name: 'Nikita Herasiutsin',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'YuliyaKozlova',
    name: 'Yuliya Kozlova',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AlexeyLabotski',
    name: 'Alexey Labotski',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'KatsiarynaNovik',
    name: 'Katsiaryna Novik',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'SergeyPalagutin',
    name: 'Sergey Palagutin',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'SergeyPhilippov',
    name: 'Sergey Philippov',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AlexeyShalak',
    name: 'Alexey Shalak',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AlekseyStybuk',
    name: 'Aleksey Stybuk',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'AnnaTsykunova',
    name: 'Anna Tsykunova',
    position: 'Software engineer in Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'IlyaVialinski',
    name: 'Ilya Vialinski',
    position: 'Software development Department',
    department: 'Back End Department',
    linkedIn: '',
    post: '',
  },
  {
    image: 'EkaterinaNevmerzhytskaya',
    name: 'Ekaterina Nevmerzhytskaya',
    position: 'Designer in Software development Departmen',
    department: 'Design Department',
    linkedIn: '',
    post: '',
  },
];

export default ourLeaders